title: JB Long and Son Body Shop

email-matthew: long.matthew29@gmail.com
email-shop: [address@email.com]

description: Description of JB Long and Son Body Shop.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "" # the base hostname & protocol for your site

twitter_username: MaLong29
github_username: mtlong29

markdown: kramdown
