title: JB Long and Son Body Shop

description: Description of JB Long and Son Body Shop.

url: "http://www.jblongandsonbodyshop.com" # the base hostname & protocol for your site

sass:
  sass_dir: assets/stylesheets
  style: compressed

markdown: kramdown

gems:
  - jekyll
  - jekyll-assets